@movie_api_HostAddress = http://localhost:5215

POST {{movie_api_HostAddress}}/api/movies
Content-Type: application/json

{
  "title": "Inception"
}

###

GET {{movie_api_HostAddress}}/api/movies
Accept: application/json

###